### ISSUE TITLE
Beam dump recovery needs to switch on feedback

### ISSUE THREAD

**Issue by jilavsky** [APS-USAXS/usaxs-bluesky#566]
After suspending for beam dump the system did not switch on feedback, required manual switch on. We need to make sure that after beam comes back and we go in timeout, the feedback is running or the timeout is waste of time.

**Comment by prjemian** [comment]
There is a hook for that. I'll need to look it up.

**Comment by prjemian** [comment]
Looks like suspender works properly.  We made a decision to ignore any previous setting and just switch the feedback on when mono beam is lost and after the sleep when mono beam comes back.
